import os
import sys
import subprocess
import json
import tempfile


def _base_ytdlp_args():
    # Force the Android player client (matches your local terminal behavior).
    # You can override via env: YTDLP_PLAYER_CLIENT=web/ios/tv/etc.
    player_client = os.environ.get("YTDLP_PLAYER_CLIENT", "android")
    return ["yt-dlp", "--extractor-args", f"youtube:player_client={player_client}"]


def _normalize_cookie(cookie):
    if cookie is None:
        return {}
    if isinstance(cookie, dict):
        return cookie
    if hasattr(cookie, "dict"):
        return cookie.dict()
    return {}


def _cookies_to_netscape(cookies):
    if not cookies:
        return None

    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by YouLaugh",
    ]

    for cookie in cookies:
        data = _normalize_cookie(cookie)
        domain = data.get("domain")
        name = data.get("name")
        if not domain or not name:
            continue

        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = data.get("path") or "/"
        secure = "TRUE" if data.get("secure") else "FALSE"
        expires = int(data.get("expirationDate") or 0)
        value = data.get("value", "")

        lines.append("\t".join([domain, include_subdomains, path, secure, str(expires), name, value]))

    if len(lines) <= 2:
        return None

    temp_file = tempfile.NamedTemporaryFile(delete=False, mode="w", encoding="utf-8", newline="\n")
    temp_file.write("\n".join(lines) + "\n")
    temp_file.close()
    return temp_file.name


def has_ytdlp() -> bool:
    try:
        subprocess.run(["yt-dlp", "-h"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except:
        return False


def select_format(url: str, cookies=None):
    format_ids = []
    cookie_file = _cookies_to_netscape(cookies)

    # Fetch video info json
    try:
        cmd = _base_ytdlp_args()
        if cookie_file:
            cmd += ["--cookies", cookie_file]
        cmd += [url, "--dump-json"]

        output = subprocess.run(cmd, text=True, capture_output=True, check=True)
        output = json.loads(output.stdout)
    except subprocess.CalledProcessError as e:
        return f"{e.returncode} : {e.stderr}"
    finally:
        if cookie_file:
            try:
                os.remove(cookie_file)
            except OSError:
                pass

    # List the formats
    if "formats" not in output:
        return {"No formats available for that URL."}

    for f in output.get("formats", []):
        if f.get("vcodec") != "none":  # filter only video
            format_ids.append({
                "format_id": f.get("format_id"),
                "resolution": f.get("resolution"),
                "ext": f.get("ext"),
                "url": f.get("url")  # THIS is what frontend needs
            })

    return format_ids


def confirm_download() -> bool:
    while True:
        confirm = input("Download? [Y/N]")

        if confirm.lower() == "n":
            return False
        elif confirm.lower() in ["y", ""]:
            return True


def download_video(url: str, format_id: str, cookies=None):
    cookie_file = _cookies_to_netscape(cookies)

    command = _base_ytdlp_args()
    if cookie_file:
        command += ["--cookies", cookie_file]
    command += [url, "-f", format_id]

    try:
        subprocess.run(command, check=True)
        return {"status": "success"}
    except subprocess.CalledProcessError as e:
        return {"error": str(e)}
    finally:
        if cookie_file:
            try:
                os.remove(cookie_file)
            except OSError:
                pass

# def main():
#     if(has_ytdlp() is  False):
#        print("yt-dlp isn't installed")
#        sys.exit()

#     url = input("Enter video URL (q to quit): ")

#     if url.lower() == "q":
#         sys.exit()

#     # List formats
#     format_id = select_format(url)

#     # Confirm Download
#     if format_id != "" :
#         confirm = confirm_download()
#         if not confirm:
#             print("Download cancelled.")
#         else:
#             download_video(url, format_id)